name: ci
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-latest:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - tag: latest
            git_version: 2.32.0
            gh_version: 2.4.0

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rahilp/alpine-gh
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.context.gh_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.context.gh_version }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            git_version=${{ matrix.context.git_version }}
            gh_version=${{ matrix.context.gh_version }}
